# -*- coding: utf-8 -*-
"""Genre_Classifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1szgX5BLsXX6Ou8ilgV67K0NLyKjwq4O6
"""

!pip install datasets
from datasets import load_dataset, Audio

!pip install transformers
from transformers import pipeline, AutoFeatureExtractor, AutoModelForAudioClassification, TrainingArguments, Trainer

!pip install numpy
import numpy as np

!pip install gradio
import gradio as gr

fleurs = load_dataset("google/fleurs", "all", split="validation", streaming=True)
sample = next(iter(fleurs))

sample

sample["audio"]["array"]

model_id = "sanchit-gandhi/distilhubert-finetuned-gtzan"
pipe = pipeline("audio-classification", model = model_id)

def classify_audio(filepath):
    preds = pipe(filepath)
    outputs = {}
    for p in preds:
        outputs[p["label"]] = p["score"]
    return outputs

classify_audio(sample["audio"]["array"])

intf = gr.Interface(fn = classify_audio, inputs = gr.Audio(type = "filepath"), outputs = gr.outputs.Label())

intf.launch(debug = True, share = True)